repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
        exclude: "tsconfig.json"
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.7.0]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/pre-commit
    rev: v2.7.1
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
    -   id: isort
        name: sort python imports
        args: [--force-single-line-imports,
        --line-length=160,
        --project=farm_ng]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.0.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.5.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.6.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v6.8.0'
    hooks:
    -   id: eslint
        files: ^app/frontend/.*\.(js|jsx|ts|tsx)$
        types: []
        exclude: webpack.config.js
        additional_dependencies:
            - 'eslint@6.8.0'
            - '@typescript-eslint/eslint-plugin@2.34.0'
            - '@typescript-eslint/parser@2.34.0'
            - 'eslint-config-prettier@6.11.0'
            - 'eslint-plugin-prettier@3.1.3'
            - 'eslint-plugin-react@7.20.0'
            - 'eslint-plugin-react-hooks@2.5.0'
            - 'eslint-plugin-import@2.20.2'
            - 'prettier@2.0.5'
            - 'typescript@3.9.2'
-   repo: local
    hooks:
    -   id: proto-lint
        name: proto-lint
        language: system
        pass_filenames: false
        entry: buf lint
