version: "3.3"

# TODO(isherman):
# - Define non-host network
# - Define re-usable volume

services:
  ipc_logger:
    image: farmng/base:edge
    build:
      context: ..
      dockerfile: docker/base.Dockerfile
    entrypoint: build/modules/core/cpp/farm_ng/ipc_logger
    environment:
      - BLOBSTORE_ROOT=/blobstore
    volumes:
      - "${BLOBSTORE_ROOT:?err}:/blobstore"
    network_mode: host
  programd:
    entrypoint: ./env.sh python -m farm_ng.core.programd
    image: farmng/base:edge
    build:
      context: ..
      dockerfile: docker/base.Dockerfile
    environment:
      - BLOBSTORE_ROOT=/blobstore
    volumes:
      - "${BLOBSTORE_ROOT:?err}:/blobstore"
    network_mode: host
  webservices:
    image: farmng/webservices:edge
    build:
      context: ..
      dockerfile: docker/webservices.Dockerfile
    environment:
      - FARM_NG_ROOT=/farm_ng
      - BLOBSTORE_ROOT=/blobstore
      - PORT=8989
    volumes:
      - "${BLOBSTORE_ROOT:?err}:/blobstore"
    network_mode: host
