version: '2'
networks: {}
volumes:
  etc_data:
services:
  rtkrover:
    build:
      dockerfile: app/tractor/Dockerfile.rtkrover
      context: ./
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    expose:
      - 2023
      - 2024
      - 9797
    #ports:
    #  - "2023:2023" # uncomment only for dev
    volumes:
      - "etc_data:/etc/farm_ng"
  frontend:
    depends_on:
      - rtkrover
    build:
      dockerfile: app/tractor/Dockerfile.frontend
      context: ./
    ports:
      - "80:8080"
    volumes:
      - "etc_data:/etc/farm_ng"
  canbus:
    build:
      context: app/tractor/canbus/
    cap_add:
        - all
    privileged: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
      io.resin.features.resin-api: '1'
