version: '2'
networks: {}
volumes: {}
services:
  rtkrover:
    build:
      dockerfile: app/tractor/Dockerfile.rtkrover
      context: ./
    privileged: true
    restart: always
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports: # only for development, disable in production
      - "2023:2023"
      - "9797:9797"
    expose:
      - 2023
      - 2024
      - 9797
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
    volumes:
      - "/etc/farm_ng:/etc/farm_ng"
  frontend:
    build:
      dockerfile: app/tractor/Dockerfile.frontend
      context: ./
    restart: always
    ports:
      - "80:8080"
    volumes:
      - "/etc/farm_ng:/etc/farm_ng"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
  driver:
    build:
      context: ./
      dockerfile: app/tractor/driver/Dockerfile
    cap_add:
      - all
    privileged: true
    tty: true
    restart: always
    network_mode: host
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
