global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: metrics_demo
    static_configs:
      - targets: ["localhost:7000"]
# remote_write:
#   - url: "http://localhost:8081/receive_metrics"
