name: Nightly

# Run integration tests nightly

on:
  schedule:
    - cron: "0 9 * * *" # 9 AM UTC
  push:
    # For testing
    # TODO(isherman): remove
    tags:
      - "nightly-*"

jobs:
  onsite-tests:
    strategy:
      matrix:
        module: ["core", "perception", "calibration", "tractor"]
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build
        run:
          - ./bootstrap-venv.sh
          - ./env.sh make third_party
          - ./env.sh make protos
      - name: Test
        run: ./env.sh python -m unittest modules/${{ matrix.module }}/tests/integration_test.py
  # Something like the following could be used to run specific tests on specific hardware
  # onsensorbox-tests:
  #   strategy:
  #     matrix:
  #       module: ["perception"]
  #   runs-on: [self-hosted, sensorbox]
  # ontractor-tests:
  #   strategy:
  #     matrix:
  #       module: ["tractor"]
  #   runs-on: [self-hosted, tractor]
