name: PR CI

# For all PRs to the master branch compile the code and run static analysis
on:
  pull_request:
    branches: master

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"

      - name: Cache pre-commit's installed hooks
        uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit static analyzers
        uses: pre-commit/action@v1.0.1

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build Docs
        run: ./devel.sh make docs
      - uses: actions/upload-artifact@v2
        with:
          name: sphinx
          path: build/doc/sphinx/

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Get digest
        id: vars
        run: |
          echo ::set-output name=devel::$(cat docker/devel/devel-digest.txt)
      - name: Build Base
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/base.Dockerfile
          build-args: |
            FARM_NG_DEVEL_IMAGE=farmng/devel@${{steps.vars.outputs.devel}}
