name: PR CI

# For all PRs to the master branch compile the code and run static analysis
on:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Cache devel_home volume
        uses: actions/cache@v2
        with:
          path: .devel_home
          key: ${{ runner.os }}-x86-devel_home-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-x86-devel_home-

      - name: Start devel
        run: ./devel.sh echo "Up."

      - name: Build Docs
        run: ./devel.sh make docs

      - name: Clean
        run: ./devel.sh make clean

      - name: Build Cpp
        run: ./devel.sh make cpp

      - name: Build Webservices
        run: ./devel.sh make webservices

      - name: Run pre-commit checks
        run: ./devel.sh pre-commit run --all-files
